apiVersion: v1
kind: ConfigMap
metadata:
  name: v-bank-app
data:
  application.properties: |-
    server.servlet.session.timeout: 30m
    spring.datasource.url: jdbc:h2:mem:testdb
    spring.datasource.driverClassName: org.h2.Driver
    spring.datasource.username: sa
    spring.datasource.password:
    spring.resources.add-mappings: true
    spring.mvc.view.prefix: /jsp/
    spring.mvc.view.suffix: .jsp
    logging.level.org.springframework.web: TRACE